#ici on va essayer de modif le make file directement


camera_program:
	@gcc ./cam.cpp -lstdc++ -o miaou.o -lpthread -I/usr/include/opencv4/ 
	#@g++ ./cam.cpp -o miaou.o -lpthread -I/usr/include/opencv4/
	@echo "Poupon je crois que la cam est là"

test_obj_detect:
	@g++ ./test_odetect.cpp -o miaou_test.o -lpthread -I/usr/include/opencv4/
	@echo "Poupon is the object detection is working?"
